// TRACKER
export const TASK_TRACKING_STARTED = 'TASK_TRACKING_STARTED';
export const TASK_TRACKING_STOPPED = 'TASK_TRACKING_STOPPED';
export const TASK_NAME_UPDATED = 'TASK_NAME_UPDATED';
export const TASK_PROJECT_UPDATED = 'TASK_PROJECT_UPDATED';
export const TASK_SPENT_TIME_INCREASED = 'TASK_SPENT_TIME_INCREASED';

// LOGS
export const LOG_TASK_ADDED = 'LOG_TASK_ADDED';

// DATE
export const DATE_FORMAT = 'hh:mm:ss, (L)';
