export const TaskActions = {
  TRACKING_STARTED: 'TASK_TRACKING_STARTED',
  TRACKING_STOPPED: 'TASK_TRACKING_STOPPED',
  NAME_UPDATED: 'TASK_NAME_UPDATED',
  PROJECT_UPDATED: 'TASK_PROJECT_UPDATED',
  SPENT_TIME_INCREASED: 'TASK_SPENT_TIME_INCREASED',
};
